// Local word bank — ~600 common English words organized by difficulty
// Easy: 1-4 letters | Medium: 5-7 letters | Hard: 8+ letters

export const easyWords: string[] = [
  "the", "and", "for", "are", "but", "not", "you", "all", "can", "had",
  "her", "was", "one", "our", "out", "day", "get", "has", "him", "his",
  "how", "man", "new", "now", "old", "see", "two", "way", "who", "boy",
  "did", "its", "let", "put", "say", "she", "too", "use", "big", "cat",
  "dog", "far", "few", "fun", "god", "got", "job", "key", "lot", "low",
  "map", "may", "met", "own", "pay", "pie", "red", "run", "set", "sit",
  "six", "sky", "ten", "top", "try", "cut", "bed", "cup", "aim", "ask",
  "bay", "bow", "bus", "buy", "cry", "dim", "dip", "dry", "due", "ear",
  "eat", "egg", "end", "era", "eye", "fig", "fit", "fly", "fog", "gap",
  "gem", "gun", "gut", "gym", "hat", "hay", "hit", "hop", "hot", "hub",
  "hug", "ice", "ill", "ink", "ion", "jar", "jaw", "joy", "kid", "kit",
  "lab", "lag", "lap", "law", "lay", "leg", "lid", "lie", "lip", "log",
  "mad", "mix", "mob", "mod", "mud", "mug", "nap", "net", "nod", "nor",
  "oil", "opt", "orb", "odd", "pan", "pat", "paw", "peg", "pen", "per",
  "pet", "pin", "pit", "pop", "pot", "pro", "pub", "pun", "raw", "ray",
  "rid", "rig", "rip", "rob", "rod", "row", "rub", "rug", "sap", "saw",
  "sex", "sin", "sip", "sob", "sod", "son", "sow", "spa", "spy", "sub",
  "sum", "sun", "sup", "tab", "tag", "tan", "tap", "tar", "tax", "tea",
  "tie", "tin", "tip", "toe", "ton", "too", "toy", "tug", "tun", "van",
  "vat", "via", "vow", "war", "web", "wet", "who", "wig", "win", "wit",
];

export const mediumWords: string[] = [
  "about", "above", "after", "again", "apple", "beach", "began", "being",
  "below", "black", "blood", "blown", "board", "brain", "brand", "brave",
  "bread", "break", "brief", "bring", "broad", "brush", "build", "built",
  "burst", "catch", "cause", "chain", "chair", "chart", "check", "chess",
  "child", "china", "chunk", "civil", "claim", "class", "clean", "clear",
  "climb", "clock", "close", "cloud", "coach", "coast", "color", "coral",
  "could", "count", "court", "cover", "crack", "craft", "crane", "crash",
  "crazy", "cream", "creek", "crime", "cross", "crowd", "crush", "curve",
  "dance", "darks", "data", "death", "debut", "depth", "derby", "diary",
  "dirty", "doing", "doubt", "dough", "draft", "drain", "drama", "drawn",
  "dream", "dress", "drift", "drill", "drink", "drive", "drove", "dryer",
  "eager", "early", "earth", "eight", "elite", "ember", "empty", "enemy",
  "enjoy", "enter", "entry", "equal", "error", "essay", "event", "every",
  "exact", "extra", "fable", "faced", "faith", "false", "fancy", "fault",
  "feast", "fence", "fever", "fiber", "field", "fifth", "fight", "filed",
  "final", "first", "flame", "flash", "flick", "float", "floor", "focus",
  "force", "forge", "forth", "forum", "found", "frame", "frank", "fresh",
  "front", "frost", "fruit", "fully", "funny", "ghost", "given", "glass",
  "globe", "gloss", "going", "grace", "grade", "grain", "grand", "grant",
  "graph", "grass", "grave", "great", "green", "greet", "grief", "grind",
  "group", "guard", "guess", "guide", "guild", "guilt", "heart", "heavy",
  "hence", "herbs", "human", "image", "index", "indie", "inner", "input",
  "issue", "ivory", "joker", "judge", "juice", "juicy", "knife", "knock",
  "known", "label", "large", "laser", "later", "laugh", "layer", "learn",
  "leave", "legal", "level", "light", "limit", "liner", "local", "logic",
  "loose", "lower", "lucky", "magic", "major", "maker", "maple", "march",
  "match", "mayor", "media", "metal", "meter", "might", "minor", "minus",
  "model", "money", "month", "moral", "motor", "mount", "mouse", "mouth",
  "moved", "movie", "music", "never", "night", "noise", "north", "noted",
  "novel", "nurse", "ocean", "offer", "often", "order", "other", "ought",
  "outer", "owner", "ozone", "paint", "panel", "paper", "party", "pasta",
  "patch", "pause", "peace", "perch", "photo", "piano", "piece", "pilot",
  "pixel", "pizza", "place", "plain", "plane", "plant", "plate", "plaza",
  "plead", "point", "poker", "polar", "power", "press", "price", "pride",
  "prime", "print", "prior", "prize", "probe", "proof", "prose", "proud",
  "prove", "pulse", "pupil", "queen", "queue", "quick", "quiet", "quota",
  "quote", "radar", "radio", "raise", "range", "rapid", "reach", "ready",
  "realm", "remix", "reply", "rider", "right", "rival", "river", "robot",
  "rocky", "roman", "rough", "round", "route", "royal", "rugby", "ruler",
  "rural", "saint", "sales", "scene", "score", "sense", "serve", "seven",
  "shade", "shake", "shall", "shape", "share", "sharp", "shift", "ship",
  "shore", "short", "shout", "sight", "since", "sixth", "sixty", "sized",
  "skill", "sleep", "slice", "slide", "slope", "small", "smart", "smoke",
  "solar", "solid", "solve", "sorry", "south", "space", "spare", "spark",
  "speed", "spend", "spent", "spice", "spine", "spoke", "sport", "spray",
  "squad", "stack", "staff", "stage", "stain", "stake", "stand", "start",
  "state", "stays", "steam", "steel", "steep", "steer", "steps", "stern",
  "stick", "still", "stock", "stone", "stood", "store", "storm", "story",
  "strip", "stuck", "study", "style", "sugar", "suite", "sunny", "super",
  "surge", "swamp", "sweet", "swept", "swift", "sword", "table", "taken",
  "taste", "teach", "teeth", "theme", "there", "these", "thick", "thing",
  "think", "third", "those", "three", "threw", "night", "tiger", "tight",
  "timer", "title", "today", "token", "total", "tough", "towel", "tower",
  "trace", "track", "trade", "trail", "train", "trait", "traps", "trash",
  "treat", "trend", "trial", "tribe", "trick", "tried", "drive", "truck",
  "trunk", "trust", "truth", "tuned", "twice", "twist", "ultra", "under",
  "unify", "union", "unity", "until", "upper", "urban", "usage", "usual",
  "valid", "value", "video", "vista", "vital", "vivid", "voice", "voter",
  "watch", "water", "weave", "where", "which", "while", "white", "whole",
  "whose", "wider", "width", "windy", "witch", "woman", "words", "world",
  "worse", "worst", "worth", "would", "write", "wrong", "yield", "young",
  "youth", "zones",
];

export const hardWords: string[] = [
  "absolute", "abstract", "academic", "accurate", "achieve", "acquired",
  "activity", "actually", "addition", "adequate", "adjacent", "adjusted",
  "advanced", "affected", "although", "analysis", "announce", "anything",
  "apparent", "approach", "approval", "argument", "arranged", "assembly",
  "assigned", "attached", "attitude", "audience", "balanced", "barriers",
  "behavior", "birthday", "blessing", "branches", "browsing", "building",
  "calendar", "campaign", "capacity", "captured", "category", "centered",
  "ceremony", "chapters", "children", "circular", "civilian", "climbing",
  "clinical", "combined", "compact", "complete", "composed", "computer",
  "concepts", "concerns", "conflict", "contains", "continue", "contrast",
  "convince", "coverage", "creative", "cultural", "currency", "customer",
  "database", "deadline", "decision", "declared", "delivery", "describe",
  "designed", "detailed", "dialogue", "diamonds", "diligent", "directly",
  "distinct", "document", "dominant", "dramatic", "duration", "economic",
  "educated", "elements", "emerging", "emotions", "emphasis", "employed",
  "encoding", "enhanced", "entirely", "entrance", "equation", "estimate",
  "evaluate", "evidence", "examples", "exercise", "expected", "explicit",
  "extended", "external", "familiar", "featured", "feedback", "flexible",
  "followed", "football", "function", "generate", "generous", "globally",
  "gradient", "graphics", "grateful", "greatest", "guidance", "hardware",
  "headline", "honestly", "hospital", "identity", "imagined", "improved",
  "included", "increase", "industry", "infinite", "informal", "instance",
  "intended", "interest", "invasion", "keyboard", "language", "learning",
  "likewise", "limiting", "lockdown", "location", "maintain", "majority",
  "matching", "maximize", "measured", "medicine", "memories", "minimize",
  "minority", "moderate", "momentum", "mountain", "movement", "multiple",
  "navigate", "negative", "normally", "observed", "offering", "official",
  "optional", "ordinary", "organize", "original", "outlined", "overcome",
  "patience", "patterns", "peaceful", "personal", "physical", "possible",
  "powerful", "practice", "previous", "probably", "produced", "progress",
  "provided", "publicly", "purchase", "question", "recently", "recovery",
  "referred", "relative", "relevant", "research", "resource", "response",
  "restored", "resulted", "returned", "revealed", "rhetoric", "scenario",
  "security", "selected", "separate", "sequence", "services", "settings",
  "shortage", "simulate", "singular", "situated", "software", "solution",
  "specific", "spectrum", "standard", "strength", "suitable", "superior",
  "survival", "template", "terminal", "thousand", "timeline", "together",
  "tracking", "training", "transfer", "ultimate", "umbrella", "universe",
  "validate", "variable", "whatever", "whenever", "wireless", "workflow",
];
